version: "3.9"

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pompon-bot
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - DATABASE_URL=postgres://postgres:password@db:5432/pompon
    depends_on:
      - db
    restart: always
    networks:
      - pompon-network

  db:
    image: postgres:15
    container_name: pompon-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pompon
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - pompon-network

volumes:
  postgres_data:

networks:
  pompon-network:
    driver: bridge
